services:
  postgres:
    build: ./postgresql
    env_file:
      - ./postgresql/.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
      - ./postgresql/data:/var/lib/postgresql/data
